Bumped PHP requirement
ibexa/post-install pull request #27
Opened 2021-12-10 10:59 UTC by konradoboza

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-XXXX](https://issues.ibexa.co/browse/IBX-XXXX)
| **Type**                                   | feature/bug/improvement
| **Target Ibexa version** | `v4.x` - please update `x` accordingly
| **BC breaks**                          | yes/no

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ibexa/engineering`).

2021-12-10 14:35 UTC, konradoboza commented
Fixing code style has been moved to another job. The plan is to mimic this behavior in other repositories, so any POV would be appreciated.

2021-12-11 13:05 UTC, adamwojs approved these changes

2021-12-13 11:39 UTC, Steveb-p requested changes

2021-12-13 11:39 UTC, Steveb-p commented on .github/workflows/ci.yaml
> +
`ibexa/post-install` does not make use of commercial, non open source packages.

```suggestion
```

2021-12-13 11:39 UTC, Steveb-p commented on .github/workflows/ci.yaml
> +          - '8.0'
If this step works with PHP 8.0, then the unit tests executed below should not `--ignore-platform-req php` anymore for PHP 8.0, possible 8.1 as well.

2021-12-13 11:48 UTC, Steveb-p approved these changes

2021-12-13 12:07 UTC, merged